# Generated by Django 3.2.2 on 2021-12-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(default='0000000', editable=False, max_length=13)),
                ('cTop', models.CharField(default='0000000', editable=False, max_length=10)),
                ('cMdl', models.CharField(default='0000000', editable=False, max_length=10)),
                ('cBtm', models.CharField(default='0000000', editable=False, max_length=10)),
                ('is_right_callNumber', models.BooleanField(default=True)),
            ],
        ),
    ]
